### ISSUE TITLE
导入sql文件后，迁移数据库报错

### ISSUE THREAD

**Issue by Henry-Jia** [mtianyan/Mxonline3#20]
导入mxonline2.sql到数据库后，运行`python manage.py migrate`会出现如下错误：
`django.db.migrations.exceptions.InconsistentMigrationHistory: Migration users.0001_initial is applied before its dependency auth.0009_alter_user_last_name_max_length on database 'default'.·`
数据库文件貌似需要修改

**Comment by mtianyan** [comment]
不需要导入数据库。执行migrations migrate 即可
