### ISSUE TITLE
项目结构不合理，不尊重Xadmin的版权。

### ISSUE THREAD

**Issue by ramwin** [mtianyan/Mxonline3#24]
根据官方的 [How to write reusable apps](https://docs.djangoproject.com/en/3.0/intro/reusable-apps/#your-project-and-your-reusable-app) 文档，推荐的结构是app直接放在根目录下，而不是放在apps下面。  
就算你是想放在一个自己的文件夹，也不能用apps来作为目录名啊。因为每个app下面也有一个apps.py，这样命名完全冲突了。慕课网这么教的吗？

**Comment by ramwin** [comment]
templates和static文件夹的放置我就不说了，可能还没教到app的模块化。  
但是希望慕课网不要误人子弟，至少整个项目的结构不要弄错。

**Comment by ramwin** [comment]
最让人非常气愤的一点:
Xadmin的[版权](https://github.com/sshwsfc/xadmin/blob/master/LICENSE)规定了，如果使用他们的代码需要保留版权信息并完全开源。这里在`extra_apps`里面用了Xadmin的代码不仅不保留开源信息，还留一个自己的QQ群号让人进入（可能用于商业目的）。完全不尊重xadmin的代码贡献者们和开源协议。请
1. 在`extra_apps`里注明xadmin的版权信息和官方链接。或者
2. 删除Xadmin的源码，使用链接来引入，引导大家去xadmin[官方repository](https://github.com/sshwsfc/xadmin)提交bug.

**Comment by mtianyan** [comment]
@ramwin  个人学习慕课网课程写的项目，qq群就是交流发发表情包，维护精力有限，欢迎PR 指教。

**Comment by mtianyan** [comment]
@ramwin  个人对于编写可复用app实践较少，日常一把梭，大佬如果可以重构优化项目结构，那一定太好了，诚恳邀约。
