### ISSUE TITLE
django2.0之后authenticate函数加了个request参数

### ISSUE THREAD

**Issue by Bob-Yuan** [mtianyan/Mxonline3#25]
具体在users/view.py下：
class CustomBackend(ModelBackend):
    def authenticate(self, **request**, username=None, password=None, **kwargs):

改完以后就可以把settings中的30-35行放开注释了
```
# Application definition 注册我们的app
# 设置邮箱和用户名均可登录
# AUTHENTICATION_BACKENDS = (
#     'users.views.CustomBackend',
#
# )
```

另：一个小bug是templates\org-list.html页面32行city.id应该是city_id

**Comment by mtianyan** [comment]
非常感谢，确实这几个地方都存在问题，已经一一改正。
