### ISSUE TITLE
organization中的课程数course_nums未作处理

### ISSUE THREAD

**Issue by undeadfrost** [mtianyan/Mxonline3#3]
organization中的课程数course_nums未作处理

**Comment by Jiahe-J** [comment]
参考Mxonline2代码库里courses app下的adminx里course类的save_model方法，重写了存储方法，Mxonline3中暂未更新

**Comment by undeadfrost** [comment]
重写存储方法，修改和新增可以统计，删除和批量删除也可以吗？

**Comment by Jiahe-J** [comment]
请看这里，重写delete_model方法
https://github.com/sshwsfc/xadmin/blob/master/xadmin/views/delete.py

**Comment by undeadfrost** [comment]
又想出来一种方法，在views.py中通过org_all.annotate(course_count=Count('course')).order_by('-course_count')将课程数排序，在模板中通过{{ org.course_set.count }}获取课程数
