### ISSUE TITLE
mtianyan老师，关于inlines入参的问题

### ISSUE THREAD

**Issue by SlovEnt** [mtianyan/Mxonline3#4]
在course里，course使用inlines入参，关联课程，展开course可以看到关联的课程，但是点击加号的时候，值能看到页面下放有要增加的新字段，但是不能显示完整页面，不知道您这边可以吗？演示地址xadmin用户和密码可以公开吗

**Comment by Jiahe-J** [comment]
详见
https://github.com/sshwsfc/xadmin/issues/491

**Comment by SlovEnt** [comment]
Jiahe-J老师，牛，搞定了！！
